name: Flutter CI/CD with Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: 'true'

      - name: Flutter Version
        run: flutter --version

      - name: Flutter Pub Get
        run: flutter pub get

      - run: flutter build apk

      - run: flutter build appbundle
