name: Flutter CI/CD with Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Cache Flutter SDK
      - name: Cache Flutter SDK
        id: flutter-cache
        uses: actions/cache@v3
        with:
          path: $HOME/flutter
          key: flutter-3.24.0-${{ runner.os }}
          restore-keys: |
            flutter-

      - name: Install Flutter
        if: steps.flutter-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.24.0 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
        env:
          PATH: $HOME/flutter/bin:$PATH

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-caches-${{ runner.os }}
          restore-keys: |
            gradle-caches-

      # Step 4: Setup Flutter environment
      - name: Flutter Doctor
        run: flutter doctor
        env:
          PATH: $HOME/flutter/bin:$PATH

      # Step 5: Fetch Flutter dependencies
      - name: Flutter Pub Get
        run: flutter pub get
        env:
          PATH: $HOME/flutter/bin:$PATH

      # Step 6: Build Android App Bundle
      - name: Build Android App Bundle
        run: flutter build appbundle --release
        env:
          PATH: $HOME/flutter/bin:$PATH

      # Step 7: Upload Build Artifact (Optional)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-app-bundle
          path: build/app/outputs/bundle/release/*.aab
