name: Flutter CI/CD with Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: 'true'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            sub-project/*.gradle*
            sub-project/**/gradle-wrapper.properties

      - run: ./gradlew build --no-daemon

      - name: Flutter Version
        run: flutter --version

      - name: Flutter Pub Get
        run: flutter pub get

      - run: flutter build apk

      - run: flutter build appbundle
